name: client
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  bloc: ^7.2.1
  cached_network_image: ^3.1.0
  circular_profile_avatar: ^2.0.5
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.0
  equatable: ^2.0.3
  event_bus: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.3
  flutter_image_compress: ^1.1.0
  flutter_screenutil: ^5.0.0+2
  flutter_spinkit: ^5.1.0
  flutter_svg: ^0.22.0
  get_it: ^7.2.0
  google_fonts: ^2.1.0
  hive_flutter: ^1.1.0
  image_cropper: ^1.4.1
  image_picker: ^0.8.4+2
  intl: ^0.17.0
  logger: ^1.1.0
  overlay_support: ^1.2.1
  page_transition: ^2.0.2
  provider: ^6.0.1
  route_animation_helper: ^2.0.0+7
  shared_preferences: ^2.0.11
  pin_code_fields: ^7.3.0
  fl_chart: ^0.40.6
  country_picker: ^2.0.9

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher_icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  image: "assets/images/splashscreen.png"
  color: "#10375C"
  color_dark: "#10375C"
  android: true
  ios: true

jsonToDart:
  outputFolder: lib/models #default: lib/
  typeChecking: true #default: undefined (Select from picker)
  nullValueDataType: String #default: dynamic
  nullSafety: true #default: false
  copyWithMethod: false #default: false
  mergeArrayApproach: false #default: true

flutter:

  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/
